# Uncomment the next line to define a global platform for your project
 
platform :ios, '9.0'

target 'CloudMusic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'RxCocoa'
  pod 'MBProgressHUD'
  pod 'HandyJSON'
  pod 'Moya', '14.0.0-alpha.1'
  
  #常用加密算法实现
  #aes,sha,md5
  pod 'CryptoSwift','1.0.0'
  
  

  target 'CloudMusicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CloudMusicUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
